### ISSUE TITLE
Proposal: Power OFF button

### ISSUE THREAD

**Issue by antonio1475** [jonathonlui/esphome-ikea-uppatvind#7]
I realized than by long-pressing the button, it powers off. No need to cycle through the speeds...

A Power Off can be added to the button section:

```
button:
  - platform: output
    name: "Increase speed"
    output: output1
    duration: 100ms
    id: button_press
    icon: mdi:fan-chevron-up
  - platform: output
    name: "Power Off"
    output: output1
    duration: 2s
    id: power_off
    icon: mdi:fan-off
```

1s wasn't enough, so I went straight to 2s.

I also renamed the normal button to Increase Speed, which is mostly its funciton (although it also turns off after speed 3...) and added icons:

![image](https://github.com/jonathonlui/esphome-ikea-uppatvind/assets/63130724/82f2785f-2aa9-4449-9cec-d6c3a6d54628)
